### ISSUE TITLE
conflit shortcuts with some extension

### ISSUE THREAD

**Issue by zsq2010** [ufb/Textmarker#106]
this great extension might conflict with some extension.

when I fresh install it all works well.
and when I install more tool,I guess,one of the influencing tool could be vimuim which is another tool having single key shortcut keys.

now i cannt use shift+d,and,alt up,and alt down.

and it would be useful to have a shortkey to turn on or off,to switch between conflict tool as well

thx for great work

**Comment by ufb** [comment]
Hi @zsq2010,
> it would be useful to have a shortkey to turn on or off

You can change or disable any Textmarker shortcut on Settings > Shortcuts:

![shortcuts](https://user-images.githubusercontent.com/17272252/78888160-6699e700-7a61-11ea-99de-0f728432c3db.jpg)

**Comment by zsq2010** [comment]
nice instruction!!
I really want to keep it usable all the time,without pausing
single key is great,just keep
