### ISSUE TITLE
User plugin API [split from #108]

### ISSUE THREAD

**Issue by ufb** [ufb/Textmarker#110]
this issue is a split from #108 

> some user plugin api,maybe,developers can help improving

**Comment by ufb** [comment]
@zsq2010,
could you please explain further what you have in mind? Thanks

**Comment by zsq2010** [comment]
my pleasure for great tool

I  reviewed my mind,

at the beginning,i just consider to use collected data,which now  is the json format.
use that a file shape,i can import into other tools to analysis.
it takes steps

more fluent way is having a backend support like online api,but it plus a server.
it takes much more effort

i just work out anthor way----what about injecting user script 
develops can help you to achieve different needs and you can learn from them

the key technical point is solving a problem,how to get the data and how to use right now,without a server
And do we need a server,at last,multi-platform need,and this could be a start on achieve much needs and help the platform---the tool

**Comment by ufb** [comment]
> at the beginning,i just consider to use collected data,which now is the json format.
use that a file shape,i can import into other tools to analysis.

Sorry, I don't understand what you mean

> backend support like online api,but it plus a server

For now I would rather not use a server behind Textmarker. In the future I will think about options on how to improve storage etc., though..

> what about injecting user script

No, too much effort

> develops can help you to achieve different needs and you can learn from them

That's what this open GitHub entry is for;)

> the key technical point is solving a problem

Sorry, I didn't get which problem you mean

>  And do we need a server,at last,multi-platform need,and this could be a start on achieve much needs and help the platform

Yes, server would be great for many things, but this is an unpaid project and I don't want to expand it even further, since maintaining, adding features, fixing bugs, keeping up with Firefox changes.. it's already too much work haha

**Comment by zsq2010** [comment]
really huge work.i just talk about some possibilities 
start with some a little effort whick can improve much user experience
for me,now is almost good enough.

another suggetion,about which to take fist,is:if other outer tool can solve problem,
we can delegate to that tool
for example, i can export json,and  json 2 excel with online converting tool really exiting now
then i can analysis some or sort.though the flow is not the best way,but it is acceptable

really like this tool,to say so much always
