### ISSUE TITLE
[bug] select and text-sytle cleared

### ISSUE THREAD

**Issue by zsq2010** [ufb/Textmarker#119]
for example,

highlighted a sentence which was background-colored to be yellow,
and then,I move my mouse onto that sentence again
the background color just disappeared

it might be that the **select-action** affect the **range** or **sth**  used to define the colored area.

it **only** happend on multi highlighter drawing on the shared area by them.
just clear the background.

if this happended,i can reload page to get all the color back.

this happend on after months of usage,the earlier time didn't happend such situation.

**Comment by ufb** [comment]
> highlighted a sentence which was background-colored to be yellow,
and then,I move my mouse onto that sentence again
the background color just disappeared

On which website?

> it might be that the select-action affect the range or sth used to define the colored area.

> it only happend on multi highlighter drawing on the shared area by them.
> just clear the background.

I don't understand what you mean, sorry

In principle the Textmarker script is not the only one that can change the page's content - the scripts of the page itself can do that too, of course. So it would be helpful to know on which site this happened to investigate what happens why;)

**Comment by zsq2010** [comment]
it might conflict with some extension.
now on another pc,it works well
