### ISSUE TITLE
Please put support link to this page in your Firefox addon page

### ISSUE THREAD

**Issue by piecevcake** [ufb/Textmarker#125]
Otherwise it looks like we can only email for support and you get bug reports in your reviews!

**Comment by ufb** [comment]
On contact page:
![support-link-2](https://user-images.githubusercontent.com/17272252/82764250-bebc5b00-9e0d-11ea-8f8f-5c84611943ad.jpg)
On all pages:
![support-link-3](https://user-images.githubusercontent.com/17272252/82764252-bf54f180-9e0d-11ea-9a96-06ee4065d8c0.jpg)
In dropdown menu:
![support-link-4](https://user-images.githubusercontent.com/17272252/82764254-bfed8800-9e0d-11ea-9fc6-9ef3b875325a.jpg)

**Comment by piecevcake** [comment]
This is your FIREFOX addon page
![support site missing @2020 05 25, 09_02_44](https://user-images.githubusercontent.com/32110576/82765030-6f0a7d80-9e67-11ea-9ed0-290f68bc1989.png)

should be 
![support site example @2020 05 25, 09_06_58](https://user-images.githubusercontent.com/32110576/82765040-7cc00300-9e67-11ea-8931-9512a067298e.png)

**Comment by ufb** [comment]
Oh I see. Haven't noticed this option - will add it asap.
So far I have the support link on that same page here:
![support-link-5](https://user-images.githubusercontent.com/17272252/82765105-19f14c00-9e14-11ea-80dd-af01ae4ce126.jpg)

**Comment by ufb** [comment]
done. added the support link. Haven't seen it on the product edit page, because the field there is called "website"^^

**Comment by piecevcake** [comment]
:)

**Comment by ufb** [comment]
Ah, so now both "Homepage" and "Support site" (interally called "Homepage" and "Website") are both linking to GitHub
