### ISSUE TITLE
[feature] Open the sidebar through a configurable shortcut key

### ISSUE THREAD

**Issue by rubcap** [ufb/Textmarker#136]
**Is your feature request related to a problem? Please describe.**
The Textmarker sidebar offers a lot of options for managing highlights and notes. Opening the sidebar through the context menu feels clumsy.

**Describe the solution you'd like**
A simple, configurable shortcut key for opening the Textmarker sidebar on any page. If you really want to keep the "Open sidebar" option in the context menu, separate it from page actions like "Add note", "Bookmark" through a separator line. Possibly a setting to open the sidebar automatically if you have added highlights or notes before on a web page.

**Describe alternatives you've considered**
"Open sidebar" in context menu. Too many clicks, doesn't work for me.

**Additional context**
/

**Comment by ufb** [comment]
Hey, no problem, will add a shortcut with next release.
Whereas Textmarker uses only custom built shortcuts so far, which will only work inside a page, I'll introduce a system command for toggling the sidebar - the downside with those is that I cannot disable them by default. So whatever key combo I choose will interfere with an already existing event handler for that combo (either from FF itself or from another extension) - i.e. ctrl+T and ctrl+shift+T are already taken by FF and I don't want to interfere with that.
I might choose Ctrl+Alt+T..

> If you really want to keep the "Open sidebar" option in the context menu, separate it from page actions like "Add note", "Bookmark" through a separator line.

Nah, I'm agnostic
Btw: To avoid having to enter Textmarker's submenu in the context-menu you can do the right-click on the tab (the place where the page's title and favicon are being displayed) -> there you'll only have one Textmarker context menu item - which is the one for the sidebar ;)

> Possibly a setting to open the sidebar automatically if you have added highlights or notes before on a web page.

Rather not

**Comment by ufb** [comment]
I checked the command lists for FF and Mac:

Ctrl + Alt + T seems OK
MacCtrl + Shift + T for Mac

But open for different suggestions

**Comment by ufb** [comment]
5.3.0 has been released just now. It offers a shortcut for toggling Textmarker's sidebar.
Ctrl + Alt + T
On Mac: MacCtrl + Shift + T
Note: It's not configurable (yet)

**Comment by 0rtz** [comment]
Please make shortcut configurable 🙏
I use Ctrl + Alt + T in Tranquility plugin

**Comment by ufb** [comment]
@0xRZ You can actually configure all your extension shortcuts (didn't know it myself until recently^^):
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

The addons page will look sth like this:
![Screenshot_2023-04-17_12-46-01](https://user-images.githubusercontent.com/17272252/232462582-d0852020-7b9d-4f5e-8f29-d685ceea1990.png)

**Comment by 0rtz** [comment]
@ufb thanks. Did not know this
