### ISSUE TITLE
Choose other search engine than Wikipedia for "w" shortcut

### ISSUE THREAD

**Issue by fxmarty** [ufb/Textmarker#138]
Hi,

First thanks a lot for this amazing addon. I've discovered there's also a feature to open selected text with "w" into Wikipedia in a new tab. I wanted to change this to use an other search engine, so I downloaded the source, replaced Wikipedia by my own search engine, but now it looks like Firefox doesn't support anymore sideloaded addons via xpi files.

So I think I can not do this on my own unless I go through the verification process of Firefox, am I correct?

This aside, I haven't been able either to load the module into about:debugging from source, downloading zip and renaming as .xpi. But I'm a newbie so it may be on my side. I tried both with the whole repo into an xpi, and just the "extension" folder into an xpi. In both case I get an error `File /blabla/Textmarker-master.xpi does not contain a valid manifest`.

Thanks!

**Comment by ufb** [comment]
Hi fxmarty,

> replaced Wikipedia by my own search engine

What do you mean by that?

Does your "own search engine" have public page with search-term specific URLs?
Textmarker is building the Wikipedia URL like so:
https://[lang].wikipedia.org/wiki/[searchterm]
So if your language setting is English and your search term is "blabla" Textmarker will open https://en.wikipedia.org/wiki/blabla for you.
But You can customize which search page to use on the settings page under "Misc". There are 2 input fields that let you create your own URL pattern:
https://.....searchterm.....
So you could have https://www.ecosia.org/search?tt=mzl&q=searchterm or https://duckduckgo.com/?t=ffab&q=searchterm&ia=images or any other URL pattern that starts with https://

**Comment by fxmarty** [comment]
Thank you for your answer. I indeed meant to use an other search engine as duckduckgo, etc. I didn't explore thoroughly enough the "misc" tab and missed the option to change the search engine. Sorry for the bother, it is now working exactly as I hoped it to. Thank you!

**Comment by ufb** [comment]
Happy to help :)
