### ISSUE TITLE
a Version for Chrome browser + ability to sync with Firefox and vice versa

### ISSUE THREAD

**Issue by JoeyBorda** [ufb/Textmarker#139]
I use _multiple_ browsers, as I have found typically each has a feature/ability to do something better than the others (if they can do them at all) , e.g. natively, creating more accurate whole-page PDFs including working URL links (or at least better than Firefox; they have no in-built native ability, and the available extensions are horrible, leaving aside my dislike of profiteering Adobe and refusal to use anymore) E.G., **_SlimJet by Flashpeak_**, which I use instead of Google Chrome, yet virtually identical to Chrome & uses their extensions. I would love to have a **_Textmarker_** version **_for Chrome_** with the ability to sync with Firefox, and vice versa, if achievable securely. **_Thanks_** for hearing me out. /s/ _**Joey**_

[2020-06-23-1733-Tue]

**Comment by malte-open** [comment]
Hi @JoeyBorda 
Please see [this issue](https://github.com/ufb/Textmarker/issues/132)

**Comment by ufb** [comment]
Hi @JoeyBorda 
Please see [this issue](https://github.com/ufb/Textmarker/issues/132)

**Comment by JoeyBorda** [comment]
Thanks everyone !  /s/ All my relations...
