### ISSUE TITLE
Highlighting text in online PDF

### ISSUE THREAD

**Issue by lmWinifred** [ufb/Textmarker#18]
Hey,

Your tool looks really polished and easy to use. (I just installed it). I tried to highlight text parts in online PDFs, but it didn't work. Is it possible with your tool? Did I miss something to enable in the setup? 
If not, would be lovely to be able to do that.

Cheers and thanks for that lovely tool!
Winifred

**Comment by ufb** [comment]
Hi Winifred,
Textmarker used to work in PDF viewer, but Firefox doesn't allow extension to run in PDF viewer anymore.
There is nothing we can do about it
