### ISSUE TITLE
[bug] Error occured when try to delete hisotry entry

### ISSUE THREAD

**Issue by ameaninglessname** [ufb/Textmarker#184]
**Describe the bug**
Can't delete any history entry

**To Reproduce**
Try to delete any history entry

**Expected behavior**
I want to delete all synced entries and adopt the manually import / export method because the Firefox default storage is too small.

**Screenshots**
![image](https://user-images.githubusercontent.com/20263103/181879517-569e91f8-2254-4005-a6ad-4d7955a7ff9a.png)

**Which OS, Firefox edition, Textmarker version**
These infos could be helpful in order to reproduce the buggy behavior
OS (i.e. Linux, MacOS, Win7, Win10, Android ...):
Edition	Windows 11 Pro
Version	21H2
Installed on	‎4/‎28/‎2022
OS build	22000.832
Experience	Windows Feature Experience Pack 1000.22000.832.0

FF edition (i.e. Regular, Nightly, ESR, ...): Firefox 103.0
Textmarker version (i.e. 5.1.2): 5.3.1

**Comment by ufb** [comment]
I'm sorry - this seems to be one of the few errors that we don't store error details for.
Unfortunately I can't help with this bug :/

**Comment by ameaninglessname** [comment]
> 

Never mind, thanks for you reply.

It turns out an issue for cloud storage limit for Firefox.

I've solved it by manually deleted the cloud storage of this add-on (after backup my data) using [aboutsync](https://github.com/mozilla-extensions/aboutsync)
