### ISSUE TITLE
Add an option to view a summary of highlight texts

### ISSUE THREAD

**Issue by dbogdanov** [ufb/Textmarker#20]
Currently there is an option to download the highlighted text. It will be nice to add another option to able to view the summary of highlights for a note in the browser.

**Comment by ufb** [comment]
@dbogdanov Hi, unfortunately I'm not quite sure what you mean by 

> to view the summary of highlights for a note in the browser.

Can you please explain it in more detail?

Thx:-]

**Comment by dbogdanov** [comment]
@ufb I imagine opening a new page where you can see all the highlighted text fragments for a webpage without the rest of the original text.

**Comment by ufb** [comment]
@dbogdanov You have that already since version 3.6.0 -> being on Textmarker's history page just click on the small icon right next to the entry name ;-]
![detailwindowlink](https://user-images.githubusercontent.com/17272252/46136526-1923a380-c248-11e8-96f2-43a3d4121eee.jpg)

**Comment by dbogdanov** [comment]
Oh, that's great! Sorry for the mistake, I haven't realized there was this icon! (I've just started using Textmarker).

**Comment by ufb** [comment]
All good, this site is for questions like that.
Some day when I got the time I will make a small video tutorial on how to use all of Textmarker's functions;-]
