### ISSUE TITLE
[Feature Request] Have bookmarked highlights centered in the middle of the page

### ISSUE THREAD

**Issue by sleek22** [ufb/Textmarker#22]
In other highlighters that I use and have used like Persistent Highlighter and Wired Marker(no longer works), the highlighted text appears centered in the middle of the page.

This allows one to see the context of the highlight without scrolling.

https://addons.mozilla.org/en-US/firefox/addon/persistent-color-highlighter/

**Comment by ufb** [comment]
You mean when the page has some header that scrolls?
This is acutally a good idea - will do that for next version.

**Comment by sleek22** [comment]
Perhaps I wasn't clear.

Say I highlight a sentence and bookmark it with Textmarker. The next time I open the page, the highlighted sentence is the first sentence in the veiwport. Since I want to know why I highlighted that sentence, I scroll the page such that the highlighted sentence is in the middle of the veiwport. Then I can see the context, both above and below, of the highlighted sentence.

In the example I gave above using Persistent Highlighter, when the page is opened, it scrolls down such that the highlighted sentence is in the center of the viewport.

Incidentally, this is how the Control-F search function works in Firefox and other browsers. When you search for a word that is outside the veiwport, the page scrolls such that the searched word is centered in the middle of the viewport.

Again, this is for purposes of context. Because you want to see the context of the highlight to understand why you highlighted it in the first page. For that, you want to see the whole paragraph containing that highlighted sentence, not just what comes after it.

As an aside, it is also more comfortable for the eyes to read in the middle of the viewport because this is where the eyes naturally rest. In my case, if I'm concentrating on something important in an article, I will scroll such that that portion of the article is centered in the viewport. Because a highlighted paragraph is important, it would be nice to have that paragraph centered in the viewport when Textmarker scrolls to a bookmark.

**Comment by ufb** [comment]
Ah, I see, thanks for the detailed explanation.
Another user emailed me that scrollable headers would cover the bookmarked highlights.
So a center position has several advantages, I guess :-]
Any of those reasons is enough by itself to implement it - will do so with next update (3.8.3) within the next 2 weeks

**Comment by sleek22** [comment]
Thanks for the quick reply and appreciate all your hard work in making this add-on.

By the way, here's another reason for centering highlights. (I'm not sure that's the same thing as scrollable headers, if so, just ignore this comment).

Load this page in your browser: https://news.harvard.edu/gazette/story/2018/10/large-scale-wind-power-has-its-down-side/

Notice how as you scroll down, a dropdown menu appears at the top of the screen. Now highlight the words "As the world begins" in the second paragraph and bookmark. Now reload the page. Notice how the bookmark is covered by that dropdown menu.

These dropdown menus have become increasing common on websites.

**Comment by ufb** [comment]
Both bookmarks and other highlights that are being scrolled to (via Textmarker buttons or automatically on page revisit) are shown center page now -> v.3.8.3
