### ISSUE TITLE
Context menu does not appear on highlighted links?

### ISSUE THREAD

**Issue by undercookedrice** [ufb/Textmarker#23]
On the latest version of Firefox, highlighted links do not give the option to select "delete highlight" on the drop down menu when right clicking the link like it does when doing the same to highlighted non-linked text. Limitation or missing feature?

**Comment by ufb** [comment]
As context type for the context menu on highlights I use `page`, but apparently that won't work for links as I've read here:

> [Applies when the user context-clicks in the page, but none of the other page contexts apply (for example, the click is not on an image or a nested iframe or a link).](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType)

So I have to use `link frame page` instead.
Don't know if that was different in previous versions of Firefox.

Will fix it with next version 3.8.3

**Comment by ufb** [comment]
fixed and released -> v.3.8.3
