### ISSUE TITLE
Doesn't work on Firefox 51 

### ISSUE THREAD

**Issue by hyh19962008** [ufb/Textmarker#3]
The menu selections, none of them responds t my click. And the shortcut does't work either.

**Comment by ufb** [comment]
Which version of Textmarker are you using?

**Comment by hyh19962008** [comment]
OK, I got 2.1.1 working.
3.0.0 to latest version doesn't work.

**Comment by ufb** [comment]
I have updated Textmarker's version history. Apparently I kept the default values for compatibility (whis is 42+) when updating new versions. Changed them for versions >=3.0.0 - they are compatible with FF57+ (maybe even lower, like FF55, but FF57+ is a sure thing;))
