### ISSUE TITLE
Renaming Highlights

### ISSUE THREAD

**Issue by betweenthefog** [ufb/Textmarker#37]
I apologize if this has been requested or is already added, but could there be an option to rename highlights? I couldn't find anything really relating to that. 

I'll give the tl;dr details below:

I'm using this as a replacement for Wired-Marker for bookmarking (or highlighting, in this case) flower seed catalogs. Some seed sites simply list seeds by type (ex: http://www.seedman.com/nasturtium.htm), making marking them necessary when comparing seed offerings between catalogs. Most I've marked them by highlighting the name and making that the highlight's name.

However, as in the example I've listed, some websites list them by variety, making it easy to lose them when I'm searching through my highlights for, say, 'nasturtium'. While I can tag them, it'd be much easier to just rename the outliers, or allow the option via right-click menu to pick whether I want to specify the name or not.

I used to use Wired-Marker to mark online seed catalogs before the jump to Quantum, and your add-on's been the only one I found that gets close to what it did. Thanks a bunch!

**Comment by ufb** [comment]
Hi betweenthefog,

so far there is no renaming option implemented. Momentarily, the closest you can get to what you'd like to accomplish is to manually name your entries (choose "Use custom name" on settings page under tab "History").

In some weeks or a couple of months there will be a major update with a lot of new features. I will check if renaming a history entry could be another new feature for that release..

Quick note to mentioned website: This seems to be some sort of shop. Please note that Textmarker might not be able to restore your highlights if the page's content changes (which seems very likely to happen in an online shop) before your next visit.

**Comment by betweenthefog** [comment]
Thanks for the quick response!  

And thank you for the warning. At least, with this system, I'll have the name of what I was looking at, so it works just as well as my alternative, which is simply making a list.

**Comment by ufb** [comment]
Uploaded 4.0.0 just now. Entries can be renamed now. Note that this feature is still experimental - if you encounter something buggy, please let me know
