### ISSUE TITLE
Mathjax support

### ISSUE THREAD

**Issue by lucgiffon** [ufb/Textmarker#40]
Hi,

textMarker isn't able to restore highlights that contains mathematical expressions written with Mathjax and then I get an error "impossible to restore".

Website example with such maths: http://cs231n.github.io/optimization-2/

I guess it is an encoding problem? Or maybe it is because there is a difference between the source html code and the actual rendered text..

Furthermore, I am not sure but it looks like once I have highlighted a math expression, all the following highlights are very buggy.

That would be awesome if you found a way to solve this.

Bye

**Comment by lucgiffon** [comment]
Thank you for this quick answer.

I certainly can wait! I've been looking for such tool for a long time now.

Even though I can't enjoy the full experience yet, thank you very much for your work. (y)

**Comment by ufb** [comment]
done. 4.0.0 still needs to be tested intensivley before its release...

**Comment by lucgiffon** [comment]
How can I test it?

**Comment by ufb** [comment]
Sorry, I meant that I have to test everything before I can release it ;-)
There are lots of new features in 4.0.0 and I just didn't find the time yet to test if everything is working as expected

**Comment by ufb** [comment]
Uploaded 4.0.0 just now - hope it works now for you with Mathjax.
Wait till Mathjax is done, then click the retry button in the sidebar.
You can disable the failure notifications - they will be shown initially, since Textmarker won't be able to restore your highlights before Mathjax is done

**Comment by lucgiffon** [comment]
It seems to work flawlessly, this is excellent. Thank you very much for your work :)

**Comment by ufb** [comment]
nice :)
