### ISSUE TITLE
support highlight in Firefox Reader View

### ISSUE THREAD

**Issue by nickylimjj** [ufb/Textmarker#42]
Are there plans to support highlighting visibility and commands when viewed in Reader View?

**Comment by ufb** [comment]
Textmarker used to work in reader view, but since Firefox is using the [WebExtensions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) extensions can't inject content scripts in reader view anymore - see [this question on Mozilla discourse](https://discourse.mozilla.org/t/accessing-about-reader-urls-in-a-webextension/17998).
This might change in the future - let's hope so;)

**Comment by nickylimjj** [comment]
I also notice syncing issues when viewing the highlighted portions on the original website and through pocket (the article manager in firefox). Will that need addressing?

**Comment by ufb** [comment]
Sorry, I don't know what exactly you mean by that

**Comment by nickylimjj** [comment]
> Sorry, I don't know what exactly you mean by that

When I highlight it an article on the website (ie, www.articles.com/donuts-will-rule-the-world) and i save it on pocket, the highlights are not viewable when i visit the article from within pocket.

Let me know if it is still unclear and I will add pictures.

**Comment by ufb** [comment]
it's different URLs. I don't use Pocket, but I think pages you save there start with `https://getpocket.com`, no? Textmarker is looking for URL-matches. Either you use the original page OR Pocket, so I would suggest to save a page to Pocket, then open it from Pocket, then do the highlights;)

**Comment by nickylimjj** [comment]
I see. What a pity! Are you interested in supporting matches on both? I think there is sufficient interest because my (and I would suppose most others) workflow would be to

1. read an article
2. Highlights interesting stuff
3. Finish and conclude it's worth saving and save it (in my cause I used pocket which is built into Firefox)

And when I refer to it next time, it is through the pocket link.

I would be down to submit a PR as well if you think it well.

**Comment by ufb** [comment]
This doesnt work. You save a page to pocket and it gets a URL that ends with a number - how is Textmarker supposed to know to which original site it refers to? Textmarker has to identify pages somehow to know if that's the page you did highlights on - and this is done via the URL. I know each Pocket site holds a link "View Original" from where the URL could be derived from and matched against your Textmarker entries - but doesnt seem the way to go for me, to rely on some 3rd party UI.
Why not saving to Pocket first, then open from Pocket, then highlight?

**Comment by nickylimjj** [comment]
Fair enough. I see. Thanks for giving this some thought!

**Comment by ufb** [comment]
Ya, sorry it's not what you were hoping for - hope you find a way to make it work for you!
