### ISSUE TITLE
Enable multiple highlighting methods simultaneously

### ISSUE THREAD

**Issue by unpack5** [ufb/Textmarker#47]
Achievable via changing the radio buttons to tick boxes in Settings > Shortcuts > Choose a highlight method.

**Comment by ufb** [comment]
In fact you can always use shortcuts and context menu, doesn't matter if you chose popup or automatically. And automatically + popup simultaneously doesnt make sense ;)

**Comment by unpack5** [comment]
Oh, yes, you are right!
