### ISSUE TITLE
No pop-up from version 4.0.1

### ISSUE THREAD

**Issue by DenB10** [ufb/Textmarker#48]
Hello,
If I choose the highlight method via pop-up, the small pop-up with markers doesn't appear.
This worked well in version 4.0.0!

**Comment by ufb** [comment]
Yep, your are right. Will be fixed asap - thank you!

**Comment by ufb** [comment]
fixed -> [commit link](https://github.com/ufb/Textmarker/commit/0c0db6b989c31c610ccf393f2cdbcb8fb1888a85)

Will be released in version 4.1.0 - coming soon

**Comment by ufb** [comment]
published
