### ISSUE TITLE
Not Working in Firefox ESR 52.8.0 (32-Bit)

### ISSUE THREAD

**Issue by Myxlplyx** [ufb/Textmarker#5]
Hi,
I just installed Textmarker, but unfortunately it is not working.

The only entry in the dropdown list that is doing something is "Pausiere Textmarker". 
Something = the icon changes
All other buttons do nothing.
Marking a text is not working
![grafik](https://user-images.githubusercontent.com/39384960/41347060-d1dfedc2-6f08-11e8-9909-2b8690717bbd.png)

Browser: 52.8.0 Firefox ESR

other addons installed:
![grafik](https://user-images.githubusercontent.com/39384960/41347225-3ea472fc-6f09-11e8-8fe7-e27fdd1b19f8.png)

**Comment by ufb** [comment]
Hi Myxlplyx,
unfortunately ESR 52 doesn't support all the new API's needed for WebExtensions yet.
![esr](https://user-images.githubusercontent.com/17272252/41350296-f8e289fc-6f12-11e8-9551-3ad3802278a5.jpg)
To my knowledge, Mozilla will switch from supporting legacy extensions to a full WebExtension support with version 60. All we can do for now is wait...;)

**Comment by Myxlplyx** [comment]
Sorry, I did not check for that!

Thanks for the quick reply.
