### ISSUE TITLE
TESTING

### ISSUE THREAD

**Issue by ufb** [ufb/Textmarker#52]
This issue is for users who'd like to help me testing new releases before they get published.
Just drop a comment below or contact me via e-mail (which you find on [Textmarker's addon-page](https://addons.mozilla.org/en-US/firefox/addon/textmarkerpro/)).

I will add a comment here each time there is a new version to test.

Instructions on how to test wil follow...

Thank you :)

**Comment by robertleeplummerjr** [comment]
I'd love to help test.

**Comment by ufb** [comment]
Thanks, I really appreciate it!
Currently Textmarker's future is unclear:
I disabled the extension some days ago, because Mozilla is more concerned about a handful of haters than about their extension developers. As for now it's completely open if I will enable it again or self-host it or simply delete it.

**Comment by robertleeplummerjr** [comment]
What did the haters hate on?

**Comment by robertleeplummerjr** [comment]
Please do not delete it, your story may be of value to many others.  I found this to be one of the most useful browser extensions I've ever used.

**Comment by ufb** [comment]
I'd prefer not to discuss this issue publicly - I can tell you more via e-mail, if you like (undflybir -> gmx net)

**Comment by ufb** [comment]
Thank you, and don't worry - I try by best to find a good solution for all the users ;)

**Comment by robertleeplummerjr** [comment]
rejected when sent.

**Comment by ufb** [comment]
sorry, undflybir at gmx dot de

**Comment by aforsyth-nz** [comment]
Happy to assist in testing new beta releases before you go live with them

**Comment by ufb** [comment]
Thanks, that's good news!

Firefox' Beta release channel system is a mess with lots of issues.
I can provide zipped pre-release versions, which can be installed in two different ways - will just copy-paste the instructions I've sent another user via e-mail:

> 1
> a) zip the extension's folder content
> b) open the page "about:debugging"
> c) click "Load Temporary Addon" and choose the zipped file
> 2
> a) like 1a) and then rename from "<anyname>.zip" (or "<anyname>.7z") to "<anyname>.xpi
> b) open one of the following Firefox editions: Developer Edition, ESR (or Nighly might work too, not sure)
> c) open the page "about:config" and set "xpinstall.signatures.required" to "false" (don't forget to revert this setting after having tested)
> d) drag&drop this file into a Firefox tab and confirm the popups
> 
> It would be good to test it on a profile where you already have Textmarker installed - but if you want to make sure nothing breaks (like your saved highlights) then it's best to use a fresh Firefox profile rahter than your default one.

I think the user who is doing the French translations is using method 2.
But I can also provide both .zip and .xpi here on GitHub by just commiting them with git.

**Comment by robertleeplummerjr** [comment]
By far the best written highlighter I have ever even used!  The new updates are simply: fantastic.


Ty for this fine plugin, your hard work.
