### ISSUE TITLE
Option: Button to start highlighting

### ISSUE THREAD

**Issue by robertleeplummerjr** [ufb/Textmarker#54]

**Comment by ufb** [comment]
What do you mean exactly? A button to enable/disable Textmarker? You can do so via Textmarker's dropdown menu in your navigation bar: Under the menu (bottom-left) there is a pause icon. Alternatively you can enable/disable the extension via addon manager.

**Comment by robertleeplummerjr** [comment]
I found it in the menu, sorry for opening this prematurely.  You have done a fine job with this project!
