### ISSUE TITLE
Firefox 66 just "disabled" it

### ISSUE THREAD

**Issue by kiers** [ufb/Textmarker#60]
could someone please help.  Love this addon. FF just disabled it for non compliance or something. Thanks.

**Comment by ufb** [comment]
Was only Textmarker disabled or all your extensions? There seems to be an FF bug disabling all extensions for some users [[read more here]](https://www.ghacks.net/2019/05/04/your-firefox-extensions-are-all-disabled-thats-a-bug/) or [[here]](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/). My FF profile is affected too, so I had to use a workaround, which is editing the `extensions.json` file - see description in link above.

**Comment by kiers** [comment]
All of them (I had only two). should i wait till FF finds its bug or do the json thing? thanks

**Comment by ufb** [comment]
I don't know how long it will take them to fix it, but probably they work on it with high pressure, since it's a big deal.

**Comment by ufb** [comment]
I think Firefox fixed the issue with version 66.0.5
