### ISSUE TITLE
Writing to the clipboard programmatically is not supported by your browser

### ISSUE THREAD

**Issue by DenB10** [ufb/Textmarker#73]
Hi,
This message (given as title) appears when I try to copy highlighted text to the clipboard.
Is it normal since I'm using Textmarker 5 under FF 60 ESR?
Thanks!

**Comment by ufb** [comment]
Yes, that's one of the things that are not implemented for ESR yet.
In fact, I added this message because of ESR (since you told me you were using it successfully with 4.1.1;)
I tested most features with ESR and am astonished that most things seem to work properly :)

**Comment by DenB10** [comment]
I thought as much! No matter, this feature isn't very important (for me).
So far, other features work well effectively.
Thank you for your quick and precise answer ;)

**Comment by ufb** [comment]
> So far, other features work well effectively

That's very good to "hear" :) Thank you for all your effort with translating and testing!

**Comment by DenB10** [comment]
You're welcome!
