### ISSUE TITLE
Notification about "couldn't save markings" appears every now and then, even when no page with marking is open

### ISSUE THREAD

**Issue by dadosch** [ufb/Textmarker#79]

**Comment by ufb** [comment]
Hi @dadosch,
can you please post the exact notification text? There are several different ones for saving errors. Does it say anything about private browsing mode?
Save failure notifications should appear whenever you try to highlight some text and have either autosave enabled or use a shortcut for saving your highlights.
If you are sure that you haven't produced any highlights, then such a notification is indeed mistaken.
There seems to be something wrong with Firefox' notification API, other users have reported strange notifications as well. For some of them it helped to uninstall and re-install Textmarker. Hope that helps for you too.
If those notifications keep annoying you then please try disabling them under Settings > Notifications
Best wishes

**Comment by ufb** [comment]
Issue unclear - need further infos.
Hope re-installation did the trick for you.
You can re-open this issue at anytime in case you want to provide more details or have further questions ;)
