### ISSUE TITLE
Errors on loading content script

### ISSUE THREAD

**Issue by ufb** [ufb/Textmarker#80]
Some users reported Textmarker's content script couldn't be loaded into some websites.
This problem couldn't be reproduced yet.
If you experienced the same please provide details here:
- URL
- OS (Linux, Win7, Win10, MacOS, Android, ...)
- FF edition (Nightly, Developer edition, ESR, ...)
- Error logs excerpt (see on Textmarker's error logs page)

Thanks

**Comment by ufb** [comment]
Released 5.1.0 just now.
Permission **Access browser activity during navigation** is mandatory now.
Plese report if you still have issues with non-loading scripts!

**Comment by aforsyth-nz** [comment]
Still having errors "**_Textmarker Content Script was not being loaded._**" on pages that have never been Textmarked.  Error occurs when closing tab.

- URL's in error log.
- OS Win10
- FF Quantum 67.0.4 (64-bit)
- Error log provided.

![Annotation 2019-07-09 213621](https://user-images.githubusercontent.com/52516165/60877528-1c959200-a292-11e9-9dd4-5e67a2fe5fe4.jpg)

**Comment by ufb** [comment]
Thank you,

> on pages that have never been Textmarked

Textmarker's content script is being loaded on all pages, also the ones that don't have saved highlights. This script is not only for restoring saved highlights, but also for being able to highlight.
You can opt-out of automatic content script loading in the settings and load it manually only on the sites you want to use it:

![manualload](https://user-images.githubusercontent.com/17272252/60880841-bafb0680-a244-11e9-9d07-ef54d5d71f29.jpg)

> Error occurs when closing tab.

This is strange, but I was able to reproduce this behavior and will investigate further.. With the next version I can just suppress this error message (always seems to have the same message: `Message manager disconnected`).
Till then I recommend to disable notifications in the settings, because even though nothing seems broken those notifications can be annoying I assume ;)

**Comment by aforsyth-nz** [comment]
Thank you for your feedback @ufb :) 
I will implement both suggestions that you proposed & will provide additional info if it becomes necessary,
I am very impressed with Textmarker and use it extensively. It is the best permanent marker / annotation tool I have used, so any bug reports I raise (whether actual or perceived) are no reflection on the usefulness of this utility, just a desire to assist in testing & providing feedback to help you make it a better product. I hope you continue to develop it and add new features as required. Keep up the good work. **Thanks**

**Comment by ufb** [comment]
Thank you, I really appreciate it!

> permanent marker

Sort of - Most users will use Textmarker on live websites that have frequently changing content. Textmarker can only indirectly find the correct text passages for restoring highlights - and this can fail, if the page's content has changed since the last visit (even if the text is still on the page: Some stored meta conditions (position relative to its parent and sibling elements) have to be met, otherwise Textmarker won't restore the highlight, by purpose, because wrong meta conditions might affect other highlights as well).

But a user can also use Textmarker on never-changing sites (downloaded website or using a service like Pocket) - for this case there is the following setting available (Settings > History):

![saveforimmut](https://user-images.githubusercontent.com/17272252/60885425-dae3f780-a24f-11e9-89ff-a0f25f52cb3c.jpg)

This will cause Textmarker to store different meta conditions and use a different algorithm for restoring highlights, which is much more bullet-proof (since one can savely assume that the page's content always is exactly the same).

**Comment by ufb** [comment]
Textmarker suppresses error notifications for the following error (which apparently happens for whatever reason on some AMP-powered pages on unload): `Message manager disconnected`.
Apparently those pages have multiple DOMContentLoaded events (they are supposed to be fast, but above example https://www.stuff.co.nz/life-style/puzzles is extremely slow). Will dig deeper and try to come up with a solution for such pages...
