### ISSUE TITLE
Forgetting Highlight Method setting?

### ISSUE THREAD

**Issue by thetoastcaper** [ufb/Textmarker#83]
in Settings → Shortcuts → "Choose a highlight method", I keep changing the setting back to "Use shortcuts or context menu for highlighting" to keep the pop-up from showing up whenever I select any text, but the setting keeps being undone, bringing the pop-up back

**Comment by sleek22** [comment]
I find that it only loses the setting after updates, which we've had a lot of recently (not complaining, just saying that is what seems to be causing it).

So after updating, I go into the setting and change it back and it seems to be sticky until the next update.

**Comment by ufb** [comment]
@sleek22 Thanks for pointing me into the right direction, so it only happens on updates then? Does it affect all your settings? @thetoastcaper Can you confirm this? Or do you lose your setting not only on updates?

I think the easiest solution would be no never update Textmarker again.
Just kidding :-D

I will have a look into this, thanks guys :)

**Comment by thetoastcaper** [comment]
I'm not certain about other settings, because I don't remember any others I've changed. I can only try to keep an eye out. 

I didn't really analyze anything very closely for this issue, but it only happens once in a while, so I wouldn't at all doubt it being caused by updates.

**Comment by thetoastcaper** [comment]
...Actually... I just realized it's also forgetting my notification settings, so yes, it does seem to be resetting more than just the highlight method setting.

**Comment by sleek22** [comment]
In my case, I don't know if other settings are being changed because I use it in a very basic way, just highlighting and deleting highlights from history when no longer needed.

**Comment by ufb** [comment]
OK, located the problem*. I can verify it for the highlight method, but all other settings (including notifications) should be fine.

(*) Silly mistake: The setting is called `markmethod` and can have one of 3 values: `"popup"`, `"auto"` and `""` (empty string) - On addon update or install Textmarker is using the default settings for the ones that are new to your addon instance. But in case of `markmethod` I didn't consider the value `""` - which leads to the wrong conclusion, that this setting is unset;)

Filx will be included in next bug-fix-release 5.1.2

**Comment by ufb** [comment]
@thetoastcaper I can only verify this bug for the highlight method, not for notification settings.
Before I ship the fix with next version, can you have a look at your notification settings and remember them for being able to tell if they persist on update?
Thanks!

**Comment by ufb** [comment]
I assume it's been fixed.
If you encounter the same problem with a different setting feel free to drop a comment below and re-open this issue.
