### ISSUE TITLE
Textmarker stopped working? Backup data, uninstall it, restart FF, re-install Textmarker

### ISSUE THREAD

**Issue by ufb** [ufb/Textmarker#84]
Some users reported that Textmarker stopped working altogether (Textmarker pages not opening etc.).
If you experience the same:

1. Export a _**backup file**_ on Textmarker's "Export & Import" page (in case you can't open the export page you could attempt a more technical approach of backing up your data -> see instructions in [comment further down below](https://github.com/ufb/Textmarker/issues/84#issuecomment-557044749))
2. Please uninstall Textmarker,
3. Restart Firefox,
4. Re-install Textmarker
5. ~~In rare cases your data won't persist across re-installation~~ -> import your backup file
**EDIT:** things have changed with FF: Whatever you do, make sure to not skip step 1 and 5

If it still doesn't work: Repeat FF-restart.
This seems to work, but as of now we don't know what is causing this issue.
~~**EDIT:** It might be related to the new permissions that have to be accepted(?)~~

**Comment by olliebean** [comment]
How do I get at the "Export & Import" page if Textmarker pages aren't opening?

**Comment by ufb** [comment]
@olliebean Did Textmarker suddenly stop working? On a Textmarker upgrade or a Firefox upgrade or just like that?

If you have made highlights that you wish to keep then try restarting FF (maybe even your OS) and see if that already does the trick.

If that doesn't work and you also haven't synced Textmarker's history entries you could skip step 1 and hope that your data will persist across re-installation (this is the case for most users). If this is too much of a gamble for you a last option for backing up your highlights is a bit technical (copy-pasted from an e-mail to another user):

- Open **about:debugging** or **about:debugging#/runtime/this-firefox** (via address bar, the same way you open any website)

- Find Textmarker and click "Inspect"

- A Toolbar will open -> open tab "Console"

- Type the following into the console (next to `>>`) to retreive your local storage in JSON format and hit Enter:

`browser.storage.local.get(null).then(data => {console.log(JSON.stringify(data))});`

- copy the output

- save output into a file that ends with **.json** (the file name doesnt matter)

- now you have your Textmarker local storage in a json file and in any FF profile with Textmarker installed you can import this storage on Textmarker's Export & Import page

**Note:** If you are not sure if your Textmarker history storage type is **local** or **sync** you can do the same procedure also with `browser.storage.sync.get().then(data => {console.log(JSON.stringify(data.history))});` The output will be empty in case you don't have synced highlights.

**Comment by olliebean** [comment]
Thanks - restarting Firefox didn't work but I was able to export via the console as you described and then re-import after uninstalling/reinstalling the add-on (the data didn't persist).

The situation was I hadn't used Textmarker for a while, and the add-on had been disabled - when I re-enabled it, I found that it wasn't working (clicking the icon produced the menu, but none of the menu entries did anything; also, the context menu was missing.) All seems to be working fine after the re-install.
