### ISSUE TITLE
How to modify URL?

### ISSUE THREAD

**Issue by chansey97** [ufb/Textmarker#85]
I'm used to downloading web pages and then using Textmarker on it.
So my question is how to synchronize URLs after moving local web page file.

For example:
I visit the website https://en.wikipedia.org/wiki/Haskell_(programming_language)
Then I download it to file:///D:/Haskell%20(programming%20language)%20-%20Wikipedia.htm
If I move this file to E:/, how to synchronize local URL in Textmarker?

Thanks for great work.

**Comment by ufb** [comment]
Hi, please see issue [URL-Migration for history entries](https://github.com/ufb/Textmarker/issues/77)
It's already on the todo list ;)
But please note: A major version has been released recently and now I'm taking a break from Textmarker development for a while.

If it's urgent then you can achieve it manually like this:

1. Download the history entry from Textmarker's history page
2. Delete the entry from the history
3. Open the downloaded entry in a text editor and change the corresp. URL
4. Import the edited entry on Textmarker's Export/Import page

Step 4 won't work without step 2

**Comment by chansey97** [comment]
I'm not very urgent :) 
I will try, when needed.
Thank you for your advice.
