### ISSUE TITLE
Suggested Improvement: Zooming and Textmarker

### ISSUE THREAD

**Issue by sahil48** [ufb/Textmarker#87]
A lot of times I zoom in or out of a website to make it easier to read the text. There are websites like Medium that blow up text on a desktop page and need to be zoomed out, and in rare cases, older websites that use the tiniest fonts imaginable, forcing me to zoom into the page. I would assume on Android (which I don't use, but from what I recall reading, textmarker supports), people will also pinch to zoom a lot.

It would be great if elements like pop-ups and sticky notes sizes adjust to accommodate for the zoom level the user goes to in their browser for reading the webpage.

**Comment by ufb** [comment]
> but from what I recall reading, textmarker support

No, never did.
Apparently there are around 100 daily users who installed it on Android anyway.
When uploading new versions I never checkmark Android support, but Firefox won't hinder users from installing it on Android - fair enough, user's freedom ;)

> It would be great if elements like pop-ups and sticky notes sizes adjust to accommodate for the zoom level 

It's up to you;)
I don't have any influence on Firefox' native zoom behavior (not that I know of that is). But you have: If you don't see notes and pop-ups grow/shrink on different zoom levels then you probably have `only zoom text` enabled (Firefox' menubar > View > Zoom)

**Comment by sahil48** [comment]
That explains it, I do a page zoom instead of only zoom text. Only zoom text works well provided that you are not dealing with extra-wide tables or multitable or fixed-column documents. Thanks!
