### ISSUE TITLE
Make quick highlight popup optional

### ISSUE THREAD

**Issue by dbogdanov** [ufb/Textmarker#89]
Is that possible to disable this popup in configuration?

![highlight](https://user-images.githubusercontent.com/409668/63957677-25803400-ca89-11e9-9e2b-5be32559b8b7.png)

**Comment by ufb** [comment]
Yes:

![disable-popup](https://user-images.githubusercontent.com/17272252/63958442-a0961a00-ca8a-11e9-9220-f92ebebc2e24.jpg)

**Comment by dbogdanov** [comment]
Thank you, I have missed that!
