### ISSUE TITLE
Bugs in version 3.6.0?

### ISSUE THREAD

**Issue by DenB10** [ufb/Textmarker#9]
Hi,
It seems there are problems with new experimental features?
- Fuzzy display in detail-view with a synced entry in the history.
- History tab : the ability to select all entries is disappeared, it's impossible to remove an assigned tag and the new action "Filter by tag" is missing.

Is it an assumed pre-behaviour with these experimental features?
Thank you,

Denis

**Comment by ufb** [comment]
hmm, that seems odd.
Would you mind to add some screenshots? You can just drag&drop them here.
In general, "select all" and "filter by tag" only appear at >= 2 entries.
Assigned tags can't be removed (yet) - that is not a bug. They can be overwritten, though. I can implement a "remove tag"-option with next release

**Comment by DenB10** [comment]
< In general, "select all" and "filter by tag" only appear at >= 2  entries. >
   OK, my great mistake: I've tested with only two history entries and more are needed.

About the fuzzy display in the detailed view, a screenshot:
![accueil_-_2018-06-16_17 37 25](https://user-images.githubusercontent.com/9309147/41500211-1952adea-717d-11e8-956c-39965ed6c5ea.png)

**Comment by ufb** [comment]
@fuzzy: Aaah, oui - a small script calculates the max width fo the left-hand texts (Créé, Titre de la page, URL, ...) and sets all widths to this max widths. I tested it just now and it seems that sometimes this is correct, sometimes not. I will fix this bug for the next release in a few days
Thank's for your help

**Comment by DenB10** [comment]
Danke schön ;)

**Comment by ufb** [comment]
we know - it was your friend fizzy;)
sorry for the confuzzyon
