### ISSUE TITLE
Can't highlight UE4 Doc and other similar websites...Why?

### ISSUE THREAD

**Issue by RemRemRemRe** [ufb/Textmarker#99]
eg:
https://docs.unrealengine.com/en-US/Programming/UnrealArchitecture/Reference/Interfaces/index.html

**Comment by ufb** [comment]
Hi @RemRemRemRe 
Thank you for your report and sorry for this late answer - currently I'm travelling and won't have time for Textmarker until April.
Just now I checked cited website and did some highlights there:

![docs](https://user-images.githubusercontent.com/17272252/74810302-5f6f1c00-52ef-11ea-9f4b-310f29db98a1.jpg)

Could you supply me with more detailed infos? I.e. you could download Textmarker's history entry for the corresponding website in .json format (-> you can do that on your Textmarker history page) and send me the file via e-mail (undflybir@gmx.de). This way I can import the file to my own Textmarker instance and see what is going wrong there (debugging it).

In case you don't feel comfortable sharing your highlights with me we'd have to tackle the issue indirectly - in this case I'd need more infos that might lead to a solution: Which OS; which Firefox edition (Regular, Mobile, Developer, ESR, ...); other examples of websites where highlighting doesn't work; does highlighting not work or only the restoration of made highlights after reload?

**Comment by RemRemRemRe** [comment]
Hi @ufb 
  Thanks for you replay. I don't know what happened, but everything works fine for me now.😂
  
  Thanks for your kind and patient comment. This plugin is really uesful and cool. Your work is amazing!
